# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  arcana2d_config = debug
  mage_config = debug
endif
ifeq ($(config),release)
  arcana2d_config = release
  mage_config = release
endif

PROJECTS := arcana2d mage

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

arcana2d:
ifneq (,$(arcana2d_config))
	@echo "==== Building arcana2d ($(arcana2d_config)) ===="
	@${MAKE} --no-print-directory -C . -f arcana2d.make config=$(arcana2d_config)
endif

mage: arcana2d
ifneq (,$(mage_config))
	@echo "==== Building mage ($(mage_config)) ===="
	@${MAKE} --no-print-directory -C . -f mage.make config=$(mage_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f arcana2d.make clean
	@${MAKE} --no-print-directory -C . -f mage.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   arcana2d"
	@echo "   mage"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"