# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  mage_config = debug
endif
ifeq ($(config),release)
  mage_config = release
endif
ifeq ($(config),dist)
  mage_config = dist
endif

PROJECTS := mage

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

mage:
ifneq (,$(mage_config))
	@echo "==== Building mage ($(mage_config)) ===="
	@${MAKE} --no-print-directory -C . -f mage.make config=$(mage_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f mage.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   mage"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"